services:
  accountsdb:
    container_name: accountsdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: microservice-db-config
  loansdb:
    container_name: loansdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: microservice-db-config
  cardsdb:
    container_name: cardsdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: mordiniaa/configserver:s7
    container_name: configserver-container
    working_dir: /app
    ports:
      - "8071:8071"
    healthcheck:
      test: curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      GIT_CONFIG_URL: ${GIT_CONFIG_URL}
      GIT_CONFIG_BRANCH: ${GIT_CONFIG_BRANCH}
      CS_ENCRYPTION_KEY: ${CS_ENCRYPTION_KEY}
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: mordiniaa/accounts:s7
    container_name: accounts-container
    restart: unless-stopped
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_DATASOURCE_URL: ${ACCOUNTS_DB_URL}
    depends_on:
      configserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: mordiniaa/cards:s7
    container_name: cards-container
    restart: unless-stopped
    working_dir: /app
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: cards
      SPRING_DATASOURCE_URL: ${CARDS_DB_URL}
    depends_on:
      configserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  loans:
    image: mordiniaa/loans:s7
    container_name: loans-container
    restart: unless-stopped
    working_dir: /app
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_DATASOURCE_URL: ${LOANS_DB_URL}
    depends_on:
      configserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  bank:
    driver: bridge