services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      timeout: 10s
      retries: 10
    extends:
      file: common-config.yml
      service: network-deploy-service
  configserver:
    image: mordiniaa/configserver:s10
    container_name: configserver-container
    working_dir: /app
    ports:
      - "8071:8071"
    healthcheck:
      test: curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      GIT_CONFIG_URL: ${GIT_CONFIG_URL}
      GIT_CONFIG_BRANCH: ${GIT_CONFIG_BRANCH}
      CS_ENCRYPTION_KEY: ${CS_ENCRYPTION_KEY}
    extends:
      file: common-config.yml
      service: microservice-base-config
  eurekaserver:
    image: mordiniaa/eurekaserver:s10
    container_name: eurekaserver-container
    working_dir: /app
    ports:
      - "8070:8070"
    healthcheck:
      test: curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: eurekaserver
  gatewayserver:
    image: mordiniaa/gatewayserver:s10
    container_name: gatewayserver-container
    restart: unless-stopped
    working_dir: /app
    ports:
      - "8072:8072"
    environment:
      SPRING_APPLICATION_NAME: gatewayserver
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATA_REDIS_CONNECTION_TIMEOUT: 2s
      SPRING_DATA_REDIS_TIMEOUT: 1s
    depends_on:
      eurekaserver:
        condition: service_healthy
      accounts:
        condition: service_healthy
      cards:
        condition: service_healthy
      loans:
        condition: service_healthy
      redis:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  accounts:
    image: mordiniaa/accounts:s10
    container_name: accounts-container
    restart: unless-stopped
    working_dir: /app
    ports:
      - "8080:8080"
    healthcheck:
      test: curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: accounts
    depends_on:
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: mordiniaa/cards:s10
    container_name: cards-container
    restart: unless-stopped
    working_dir: /app
    ports:
      - "9000:9000"
    healthcheck:
      test: curl --fail --silent localhost:9000/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: cards
    depends_on:
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config
  loans:
    image: mordiniaa/loans:s10
    container_name: loans-container1
    restart: unless-stopped
    working_dir: /app
    ports:
      - "8090:8090"
    healthcheck:
      test: curl --fail --silent localhost:8090/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      SPRING_APPLICATION_NAME: loans
    depends_on:
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  bank:
    driver: bridge