global:
  configMapName: bankqa-configmap
  activeProfile: qa
  configServerURL: optional:configserver:http://configserver:8071/
  eurekaServerURL: http://eurekaserver:8070/eureka
  keyCloakURL: http://keycloak.default.svc.cluster.local:80/realms/master/protocol/openid-connect/certs
  openTelemetryJavaAgent: "-javaagent:/app/libs/opentelemetry-javaagent-2.23.0.jar"
  otelExporterEndPoint: http://tempo.default.svc.cluster.local:4318
  otelMetricsExporter: none
  otelLogsExporter: none
  kafkaBrokerURL: kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9092
  configUrl: https://github.com/grzegMaly/microservice-course-config.git
  configBranch: main
  encryptionKey: 34HF3897EHFREIDFH8457TGAEKWDFC9348T