services:
  configserver:
    image: mordiniaa/configserver:s8
    container_name: configserver-container
    working_dir: /app
    ports:
      - "8071:8071"
    healthcheck:
      test: curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      GIT_CONFIG_URL: ${GIT_CONFIG_URL}
      GIT_CONFIG_BRANCH: ${GIT_CONFIG_BRANCH}
      CS_ENCRYPTION_KEY: ${CS_ENCRYPTION_KEY}
    extends:
      file: common-config.yml
      service: microservice-base-config
  eurekaserver:
    image: mordiniaa/eurekaserver:s8
    container_name: eurekaserver-container
    working_dir: /app
    ports:
      - "8070:8070"
    healthcheck:
      test: curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_APPLICATION_NAME: eurekaserver

  accounts:
    image: mordiniaa/accounts:s8
    container_name: accounts-container
    restart: unless-stopped
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: accounts
    depends_on:
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  cards:
    image: mordiniaa/cards:s8
    container_name: cards-container
    restart: unless-stopped
    working_dir: /app
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: cards
    depends_on:
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config

  loans1:
    image: mordiniaa/loans:s8
    container_name: loans-container1
    restart: unless-stopped
    working_dir: /app
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: loans
    depends_on:
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config
  loans2:
    image: mordiniaa/loans:s8
    container_name: loans-container2
    restart: unless-stopped
    working_dir: /app
    ports:
      - "8091:8090"
    environment:
      SPRING_APPLICATION_NAME: loans
    depends_on:
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-eureka-config

networks:
  bank:
    driver: bridge