deploymentName: eurekaserver-deployment
serviceName: eurekaserver
appLabel: eurekaserver
appName: eurekaserver

replicaCount: 1

image:
  repository: mordiniaa/eurekaserver
  tag: s14

containerPort: 8070

service:
  type: LoadBalancer
  port: 8070
  targetPort: 8070

appname_enabled: true
profile_enabled: false
config_enabled: true
eureka_enabled: false
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false
configServer: false
