services:
  accounts:
    image: mordiniaa/accounts:s4
    container_name: accounts-container
    restart: unless-stopped
    working_dir: /app
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
  cards:
    image: mordiniaa/cards:s4
    container_name: cards-container
    restart: unless-stopped
    working_dir: /app
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank
  loans:
    image: mordiniaa/loans:s4
    container_name: loans-container
    restart: unless-stopped
    working_dir: /app
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank

networks:
  bank:
    driver: bridge