apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver-deployment
  labels:
    app: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: mordiniaa/configserver:s12
          ports:
            - containerPort: 8071
          env:
            - name: CS_ENCRYPTION_KEY
              valueFrom:
                configMapKeyRef:
                  key: CS_ENCRYPTION_KEY
                  name: configserver-env
            - name: GIT_CONFIG_BRANCH
              valueFrom:
                configMapKeyRef:
                  key: GIT_CONFIG_BRANCH
                  name: configserver-env
            - name: GIT_CONFIG_URL
              valueFrom:
                configMapKeyRef:
                  key: GIT_CONFIG_URL
                  name: configserver-env
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  key: CONFIGSERVER_APPLICATION_NAME
                  name: bank-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: configserver
spec:
  selector:
    app: configserver
  type: LoadBalancer
  ports:
    - port: 8071
      targetPort: 8071
      protocol: TCP