apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver
  labels:
    app: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eurekaserver
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
        - name: eurekaserver
          image: mordiniaa/eurekaserver:s12
          ports:
            - containerPort: 8070
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  key: EUREKA_APPLICATION_NAME
                  name: bank-configmap
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  key: SPRING_CONFIG_IMPORT
                  name: bank-configmap
            - name: EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  key: EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE
                  name: bank-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: eurekaserver
spec:
  selector:
    app: eurekaserver
  type: LoadBalancer
  ports:
    - port: 8070
      targetPort: 8070
      protocol: TCP
